// TODO
// TODO support filters
//
// TODO eventCount
// TODO eventCountPerGroup
// TODO eventCountPerType
// TODO eventCountPerArea
// TODO actionDisseminatedCount(sent|issued)
// TODO actionDisseminatedPerGroup
// TODO actionDisseminatedPerType
// TODO actionDisseminatedPerArea
// TODO actionTakenCount
// TODO actionTakenPerGroup
// TODO actionTakenPerType
// TODO actionTakenPerArea
// TODO actionPendingCount
// TODO actionPendingPerGroup
// TODO actionPendingPerType
// TODO actionPendingPerArea
// TODO actionNotTakenCount
// TODO actionNotTakenPerGroup
// TODO actionNotTakenPerType
// TODO actionNotTakenPerArea
// TODO actionReceivedCount
// TODO actionReceivedPerGroup
// TODO actionReceivedPerType
// TODO actionReceivedPerArea
// TODO indicatorCount
// TODO indicatorCountPerArea
// TODO indicatorCountPerGroup
// TODO indicatorCountPerType
// TODO topicCount
// TODO topicCountPerArea
// TODO topicCountPerGroup
// TODO topicCountPerType
// TODO recentlyIssueEvent
// TODO latestUpdatedEvent
// TODO activeEvents
// TODO proneAreas
// TODO populationAtRisk
// TODO featuresAtRisk
